apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: spec-vtg-teste-demo-location
  description: Location to import all spec-vtg-teste-demo catalog components
spec:
  targets:
    - ./.platform/*.yaml
